### ISSUE TITLE
Branch report + Project filter fails

### ISSUE THREAD

**Issue by bredmold** [bredmold/nickel-scm#3]
`nickel --projects foo mergedReport merged.json` causes the following output.
```
/usr/local/lib/node_modules/nickel-scm/dist/src/actions/branch-reports.js:28
            report.candidateBranches.forEach((branch) => {
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/nickel-scm/dist/src/actions/branch-reports.js:28:38
    at Array.forEach (<anonymous>)
    at BranchReportWriter.writeReport (/usr/local/lib/node_modules/nickel-scm/dist/src/actions/branch-reports.js:27:22)
    at MergedBranchesReportAction.post (/usr/local/lib/node_modules/nickel-scm/dist/src/actions/merged-branches.js:63:120)
    at /usr/local/lib/node_modules/nickel-scm/dist/src/nickel-instigator.js:41:20
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by bredmold** [comment]
Resolved in commit 00d1a86749bd4f52e9a4d9d8d47a2e4a139493b2 - released v0.9.1
