### ISSUE TITLE
Old branches report crashes when narrowing by project

### ISSUE THREAD

**Issue by bredmold** [bredmold/nickel-scm#4]
### Repro steps
`nickel --projects someproject oldBranches old.json` 

### Expected Result
Generate a report in `old.json`

### Actual Result
```
/usr/local/lib/node_modules/nickel-scm/dist/src/actions/branch-reports.js:28
            report.candidateBranches.forEach((branch) => {
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/nickel-scm/dist/src/actions/branch-reports.js:28:38
    at Array.forEach (<anonymous>)
    at BranchReportWriter.writeReport (/usr/local/lib/node_modules/nickel-scm/dist/src/actions/branch-reports.js:27:22)
    at OldBranchesReportAction.post (/usr/local/lib/node_modules/nickel-scm/dist/src/actions/old-branches.js:50:120)
    at /usr/local/lib/node_modules/nickel-scm/dist/src/nickel-instigator.js:43:20
```

### Comments
This is almost certainly the same flavor as the issue with the merged branches report.

**Comment by bredmold** [comment]
Resolved in commit d85cecbbc27a66b636f5f7e149bf67a9a167ece2, released version 0.9.2
